# Generated by Django 5.0.6 on 2026-08-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('departamento', models.CharField(choices=[('Contabilidade', 'Contabilidade'), ('Departamento Pessoal', 'Departamento Pessoal'), ('Fiscal', 'Fiscal'), ('Legalização', 'Legalização'), ('Financeiro', 'Financeiro'), ('Contas a Receber', 'Contas a Receber'), ('Conciliações', 'Conciliações'), ('Contas a Pagar', 'Contas a Pagar'), ('Fechamentos e Resultados', 'Fechamentos e Resultados'), ('Atualização de Orçamentos', 'Atualização de Orçamentos'), ('Outro', 'Outro')], default='Contabilidade', max_length=40, verbose_name='Departamento')),
                ('frequencia', models.CharField(default='Mensal', help_text='Ex.: Mensal, Trimestral, Anual (Janeiro), Esporádico.', max_length=40, verbose_name='Frequência')),
                ('acao_qtd_dias', models.CharField(blank=True, max_length=20, verbose_name='Ação (qtd dias)')),
                ('meta_qtd_dias', models.CharField(blank=True, max_length=20, verbose_name='Meta (qtd dias)')),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Dia de vencimento')),
                ('fato_gerador', models.CharField(blank=True, help_text='Ex.: Mês anterior, Mesmo mês, Ano anterior.', max_length=40, verbose_name='Fato gerador (competência)')),
                ('orgao', models.CharField(choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal'), ('Empresa', 'Empresa')], default='Federal', max_length=20, verbose_name='Órgão')),
                ('reenvio', models.CharField(blank=True, max_length=60, verbose_name='Re-envio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['departamento', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_tarefa', to='empresas.empresa')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Vínculo empresa-tarefa',
                'verbose_name_plural': 'Vínculos empresa-tarefa',
                'ordering': ['empresa__id_sistema', 'tarefa__nome'],
                'unique_together': {('empresa', 'tarefa')},
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='empresas',
            field=models.ManyToManyField(blank=True, related_name='tarefas', through='tarefas.VinculoTarefa', to='empresas.empresa'),
        ),
        migrations.CreateModel(
            name='ExecucaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_ano', models.PositiveSmallIntegerField()),
                ('competencia_mes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('ATRASADA', 'Atrasada'), ('DISPENSADA', 'Dispensada')], default='PENDENTE', max_length=12)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='empresas.empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'Execução mensal',
                'verbose_name_plural': 'Execuções mensais',
                'ordering': ['-competencia_ano', '-competencia_mes', 'empresa__id_sistema'],
                'unique_together': {('empresa', 'tarefa', 'competencia_ano', 'competencia_mes')},
            },
        ),
    ]
