# Generated by Django 5.0.6 on 2026-08-06 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaReceitaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('sucesso', models.BooleanField(default=False)),
                ('mensagem', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log de consulta ReceitaWS',
                'verbose_name_plural': 'Logs de consulta ReceitaWS',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sistema', models.CharField(help_text='Código interno da empresa (ex.: 300, 401).', max_length=20, unique=True, verbose_name='ID no sistema')),
                ('cnpj', models.CharField(help_text='Usado para consultar a ReceitaWS.', max_length=18, unique=True, verbose_name='CNPJ')),
                ('regime_tributario', models.CharField(choices=[('SIMPLES', 'Simples Nacional'), ('MEI', 'MEI'), ('PRESUMIDO', 'Lucro Presumido'), ('REAL', 'Lucro Real'), ('IMUNE', 'Imune / Isenta')], max_length=12, verbose_name='Regime tributário')),
                ('inscricao_iss', models.CharField(blank=True, max_length=30, verbose_name='Inscrição ISS')),
                ('inscricao_icms', models.CharField(blank=True, max_length=30, verbose_name='Inscrição ICMS')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome fantasia')),
                ('situacao_cadastral', models.CharField(blank=True, max_length=60, verbose_name='Situação cadastral')),
                ('data_situacao', models.CharField(blank=True, max_length=20, verbose_name='Data da situação')),
                ('motivo_situacao', models.CharField(blank=True, max_length=255, verbose_name='Motivo da situação')),
                ('tipo', models.CharField(blank=True, max_length=30, verbose_name='Tipo (matriz/filial)')),
                ('porte', models.CharField(blank=True, max_length=60, verbose_name='Porte')),
                ('natureza_juridica', models.CharField(blank=True, max_length=255, verbose_name='Natureza jurídica')),
                ('data_abertura', models.CharField(blank=True, max_length=20, verbose_name='Data de abertura')),
                ('capital_social', models.CharField(blank=True, max_length=40, verbose_name='Capital social')),
                ('atividade_principal_codigo', models.CharField(blank=True, max_length=20)),
                ('atividade_principal_texto', models.CharField(blank=True, max_length=255)),
                ('atividades_secundarias', models.JSONField(blank=True, default=list)),
                ('quadro_societario', models.JSONField(blank=True, default=list)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('simples_optante', models.BooleanField(blank=True, null=True)),
                ('simples_data_opcao', models.CharField(blank=True, max_length=20)),
                ('simei_optante', models.BooleanField(blank=True, null=True)),
                ('status_consulta', models.CharField(choices=[('PENDENTE', 'Pendente de consulta'), ('OK', 'Consultado'), ('ERRO', 'Erro na consulta')], default='PENDENTE', max_length=10)),
                ('mensagem_consulta', models.CharField(blank=True, max_length=255)),
                ('ultima_consulta', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id_sistema'],
            },
        ),
    ]
